import JobApplication from './models/JobApplication.ts'
import type {AllRemoteOptionsType, AllStagesType, AllInterestLevelsType} from "./models/JobApplication.ts";


export const jobData: JobApplication[] = [
    new JobApplication({
        id: '1',
        company: 'Microsoft',
        position: 'Software Engineer',
        location: 'Hertzlia',
        applicationDate: '2025-02-09',
        interestLevel: 4.5 as AllInterestLevelsType,
        currentStage: 'applied' as AllStagesType,
        salaryMin: 25,
        salaryMax: 30,
        remoteOption: 'hybrid' as AllRemoteOptionsType,
        isEdit: true,
        jobUrl: 'https://jobs.careers.microsoft.com/global/en/job/1768669/Software-Engineer---Cloud-and-Enterprise-Security',
    }),
    new JobApplication({
        id: '2',
        company: 'Cybernetics Corp.',
        position: 'Backend Developer',
        location: 'Remote',
        applicationDate: '2024-11-15',
        interestLevel: 5 as AllInterestLevelsType,
        currentStage: 'technical_interview' as AllStagesType,
        salaryMin: 25,
        salaryMax: 30,
        remoteOption: 'remote' as AllRemoteOptionsType,
        isEdit: true,
        jobUrl: 'https://www.cybernetics.com/jobs/backend-dev-2',
    }),
    new JobApplication({
        id: '3',
        company: 'Creative Studio',
        position: 'UI/UX Designer',
        location: 'Chicago, IL',
        applicationDate: '2024-11-10',
        interestLevel: 3 as AllInterestLevelsType,
        currentStage: 'phone_screen' as AllStagesType,
        salaryMin: 19,
        salaryMax: 21,
        remoteOption: 'hybrid' as AllRemoteOptionsType,
        isEdit: true,
        jobUrl: 'https://www.creativestudio.com/jobs/designer-3',
    }),
    new JobApplication({
        id: '4',
        company: 'Legacy Systems',
        position: 'Systems Administrator',
        location: 'Austin, TX',
        applicationDate: '2024-10-30',
        interestLevel: 2 as AllInterestLevelsType,
        currentStage: 'rejected' as AllStagesType,
        salaryMin: 22,
        salaryMax: 34,
        remoteOption: 'onsite' as AllRemoteOptionsType,
        isEdit: true,
        jobUrl: 'https://www.legacysystems.com/jobs/sysadmin-4',
    }),
    new JobApplication({
        id: '5',
        company: 'Quantum Dynamics',
        position: 'Quantum Engineer',
        location: 'San Jose, CA',
        applicationDate: '2024-11-25',
        interestLevel: 5 as AllInterestLevelsType,
        currentStage: 'offer' as AllStagesType,
        salaryMin: 12,
        salaryMax: 23,
        remoteOption: 'hybrid' as AllRemoteOptionsType,
        isEdit: true,
        jobUrl: 'https://www.quantumdynamics.com/jobs/quantum-eng-5',
    }),
];